version: '3.3'
services:
  web:
    build: .
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    command: go run ./cmd/server/server.go
    ports:
      - "8070:8070"
      - "8090:8090"
    volumes:
      - .:/app
    networks:
      custom_network:


networks:
  custom_network:
    driver: bridge